version: '3.9'

services:
  app:
    build: .
    container_name: phase1-student-rbd
    ports:
      - "5000:8080"
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=phase1_st;Username=postgres;Password=12345678
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres-phase1
    restart: always
    environment:
      POSTGRES_DB: phase1_st
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
